config/routes.rb
PromiseTracker::Application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }
  root to: 'home#index'
  match ':status', via: [:get, :post], to: 'errors#show', constraints: {status: /\d{3}/ }

  scope "(:locale)", locale: /en|pt-BR|es|de/ do
    resources :users
    resources :campaigns
    resources :surveys, except: [:index] do
      resources :inputs
    end

    get '/surveys/:id/preview', to: 'surveys#preview', as: 'preview_survey'
    get '/surveys/test', to: 'surveys#test_builder', as: 'test_builder'
    put '/surveys/:id/save-order', to: 'surveys#save_order', as: 'save_order'
    get '/campaigns/:id/setup', to: 'campaigns#setup', as: 'setup_campaign'
    get '/campaigns/:id/goals-wizard', to: 'campaigns#goals_wizard', as: 'campaign_goals_wizard'
    get '/campaigns/:id/goals', to: 'campaigns#goals', as: 'campaign_goals'
    get '/campaigns/:id/launch', to: 'campaigns#launch', as: 'launch_campaign'
    get '/campaigns/:id/survey', to: 'campaigns#survey', as: 'campaign_survey'
    get '/campaigns/:id/profile', to: 'campaigns#profile', as: 'campaign_profile'
    get '/campaigns/:id/edit-profile', to: 'campaigns#edit_profile', as: 'edit_campaign_profile'
    get '/campaigns/:id/public', to: 'campaigns#public_profile', as: 'campaign_public_profile'
    get '/campaigns/:id/test', to: 'campaigns#test', as: 'test_campaign'
    get '/campaigns/:id/collect', to: 'campaigns#collect', as: 'campaign_collect'
    get '/campaigns/:id/share', to: 'campaigns#share', as: 'share_campaign'
    get '/campaigns/:id/close', to: 'campaigns#close', as: 'close_campaign'
    get '/campaigns/:id/next', to: 'campaigns#next', as: 'campaign_next'
    post '/campaigns/:id/activate', to: 'campaigns#activate', as: 'activate_campaign'
    post '/campaigns/:id/clone', to: 'campaigns#clone', as: 'clone_campaign'

    post '/inputs/:id/clone', to: 'inputs#clone', as: 'clone_input'

    get '/download', to: 'home#download', as: 'download'
    get '/stats', to: 'campaigns#get_stats', as: 'stats'
    get '/guides', to: 'home#guides', as: 'guides'
    get '/data/:code', to: 'campaigns#share', as: 'share_campaign_code'
    get '/codigo/:code', to: 'surveys#fill_out', as: 'fill_out_survey'
    get '/help', to: "home#help", as: 'help'
  end

  namespace :api do
    namespace :v1 do
      resources :campaigns, only: [:index, :show, :create]
      get '/users/sign_in', to: 'users#create_new_session', as: 'api_sign_in'
    end
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  belongs_to :campaign
  has_many :inputs
  before_create :generate_code

  def activate(status)
    uri = URI(ENV['AGGREGATOR_URL'] + "/surveys/#{status}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    ssl_version = :SSLv3
    request = Net::HTTP::Post.new(uri.path, {'Content-Type' =>'application/json', 'Authorization' => ENV['AGGREGATOR_ACCESS_KEY']})
    request.body = self.to_json(
      only: [:id, :code, :title, :campaign_id],
      include: { 
        inputs: { only: [:id, :label, :input_type, :order, :options, :required] }
      }
    )

    begin
      response = http.request(request)
      data = JSON.parse(response.body)

      if data['status'] == 'success'
        self.campaign.update_attributes(
          status: status,
          start_date: data['payload']['start_date'].to_datetime
        )
      end

      data
    rescue Errno::ECONNREFUSED
      { status: "error" }
    end
  end

  def close
    uri = URI(ENV['AGGREGATOR_URL'] + "surveys/#{self.code}/close")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    ssl_version = :SSLv3
    request = Net::HTTP::Put.new(uri.path, {'Content-Type' =>'application/json'})
    response = http.request(request)
    JSON.parse(response.body)
  end

  def clone
    clone = self.dup
    self.inputs.each do |input|
      clone.inputs << input.dup
    end
    clone
  end

  def get_responses
    uri = URI(ENV['AGGREGATOR_URL'] + "surveys/#{self.id}/responses")
    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Get.new(uri.path, {'Content-Type' =>'application/json'})
    response = http.request(request)
    JSON.parse(response.body)['payload'] || []
  end

  def generate_code
    begin
      self.code = rand(899999) + 100000
    end while self.class.exists?(code: code)
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!, except: [:test_builder, :new, :show, :fill_out]
  before_action :restrict_user_access, except: [:test_builder, :new, :show, :fill_out]
  layout 'survey_builder', only: [:test_builder, :edit]

  def index
    @surveys = Survey.all
  end

  def new
    if current_user
      @campaign = Campaign.find(params[:campaign_id])
      @survey = Survey.create(
        campaign_id: @campaign.id,
        title: @campaign.title
      )
      redirect_to edit_survey_path(@survey)
    else
      redirect_to test_builder_path
    end
  end

  def test_builder
    @survey = Survey.new(title: t('surveys.survey_builder.untitled'))
    @input_types = input_types.to_json
  end

  def update
    @survey = Survey.find(params[:id])
    @survey.update_attribute(:title, params[:title])

    render json: @survey
  end

  def save_order
    @survey = Survey.find(params[:id])
    inputs = params[:inputs]
    
    if inputs
      inputs.each_with_index do |input, index|
        item = Input.find_or_create_by(id: input[:id])
        item.update_attributes(input.permit(:id, :survey_id, :label, :input_type, :options, :required, :order))
        item.update_attribute(:order, index)
        item.delete if input["label"].blank?
      end
    end

    if @survey.campaign.status == 'draft'
      render json: {redirect_path: 'campaign_survey_path'}.to_json
    else @survey.campaign.status == 'test'
      @survey.activate('test')
      render json: {redirect_path: 'test_campaign_path'}.to_json
    end
  end

  def show
    @survey = Survey.find(params[:id])
    render json: @survey
  end

  def edit
    @survey = Survey.find(params[:id])
    @input_types = input_types.to_json
  end

  def fill_out
    @code = params[:code]
  end

  def destroy
    Survey.delete(params[:id])
    @surveys = current_user.surveys
    redirect_to controller: 'users', action: 'show', id: current_user.id
  end

  private

  def restrict_user_access
    @survey = Survey.find(params[:id])
    raise Exceptions::Forbidden unless current_user.owns?(@survey.campaign)
  end

end

app/views/surveys/_android_preview.html.erb
<div class="preview-container">
  <!-- ko if: PT.selectedInput -->
  <div class="input-preview" data-bind="css: PT.selectedInput().input_type">
    <div class="preview-contents">
      <div class="header">
        <%= image_tag("favicon.png") %>
        <p><%= t("app_name") %></p>
      </div>
      <div class="input">
        <p data-bind="text: PT.selectedInput().label"></p>
        <ul data-bind="foreach: PT.selectedInput().options, css: PT.selectedInput().input_type, visible: PT.selectedInput().input_type() === 'select' || PT.selectedInput().input_type() === 'select1'">
          <li data-bind="text: $data.label"></li>
        </ul>
        <div class="action-button" data-bind="visible: PT.selectedInput().input_type() === 'image' || PT.selectedInput().input_type() === 'location'">
          <span data-bind="visible: PT.selectedInput().input_type() === 'image'"><i class="fa fa-camera"></i> <%= t(".take_picture") %></span>
          <span data-bind="visible: PT.selectedInput().input_type() === 'location'"><i class="fa fa-map-marker"></i> <%= t(".get_location") %></span>
        </div>
      </div>
    </div>
  </div> 
  <!-- /ko -->
  <!-- ko ifnot: PT.selectedInput -->
  <div class="input-preview select center"></div>
  <!-- /ko -->

  <p class="center question-number"><%= t(".question") %> <span data-bind="text: PT.survey.inputs.indexOf(PT.selectedInput()) + 1"></span> <%= t(".of") %> <span data-bind="text: PT.survey.inputs().length"></span></p>

  <div class="center">
    <div class="btn btn-warning arrow" data-direction="left">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </div>

    <div class="btn btn-warning arrow" data-direction="right">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(".arrow").on("click", PT.nextInput);
</script>

app/views/surveys/_survey_body.html.erb
<div style="display: none;" data-bind="visible: true">
  <div id="survey-body">
    <ol data-bind="sortable: inputs" id="input-list">
      <li class="input" data-bind="css: { selected: PT.selectedInput() ? id === PT.selectedInput().id : false}, attr: {id: 'input' + id()}, valueUpdate: 'input'">

        <!-- ko if: inEdit -->
        <div class="modify">
          <a href="#" class="btn" data-bind="click: save"><span class="glyphicon glyphicon-floppy-disk"></span> </a>
          <a href="#" class="btn" data-bind="click: $parent.removeInput"><span class="glyphicon glyphicon-trash"></span></a>
        </div>

        <div class="row question-label">
          <div class="col-md-3 label-text">
            <%= t(".question_label") %>
          </div>
          <div class="col-md-9">
            <textarea class="form-control" data-bind="value: label, valueUpdate:'input'" placeholder="<%= t(".question_placeholder") %>" autofocus></textarea>
          </div>
        </div>

        <div class="row answer-type">
          <div class="col-md-3 label-text">
            <%= t(".answer_type") %>
          </div>
          <div class="col-md-9">
            <select class="form-control short inline" data-bind="options: PT.input_types, optionsValue: function(item) {return item.input_type}, optionsText: function(item) {return item.label}, value: input_type, event: {change: applyType}"></select>
          </div>
        </div>

        <div class="row answer" data-bind="css: input_type, visible: input_type() != 'note'">
          <div class="options label-text" data-bind="visible: input_type() == 'select' || input_type() == 'select1'">
            <div class="col-md-3">
              <%= t(".options") %>
            </div>
            <div class="col-md-9">
              <ul class="answer" data-bind="sortable: {data: options, connectClass: false, options: {handle: '.move'}}, valueUpdate:'input', css: input_type">
                <li class="option edit">
                  <input data-bind="value: label, valueUpdate:'afterkeydown'" autofocus>

                  <i class="glyphicon glyphicon-remove-sign delete-option" data-bind="click: $parent.deleteOption, visible: $parent.options().length > 1"></i>
                  <i class="glyphicon glyphicon-move"></i>
                  <div class="jump-to-expand right panel-heading" data-bind="css: {active: jump_to !== null}, attr: {'data-target': '#select-input-' + $parent.id() + '-option-' + $index()}, visible: $parent.input_type() == 'select1'" data-toggle="collapse">
                    <i class="fa fa-fw fa-chevron-down"></i>
                    <i class="fa fa-fw fa-chevron-right"></i><%= t(".advanced") %>
                  </div>
                  <br>
                  <div class="jump-to-content collapse" data-bind="attr: {'id': 'select-input-' + $parent.id() + '-option-' + $index()}, css: {in: jump_to !== null}">
                    <label class="jump"><%= t(".jump_to") %>:</label>
                    <select class="form-control short inline" data-bind="options: PT.buildJumpToArray($parent), optionsValue: function(item) {return item.id}, optionsText: function(item) {return item.label;}, optionsCaption: I18n.t('surveys.survey_body.select_question'), value: jump_to, event: { change: function() { $parent.highlightActiveJumps($data, event) } }">
                    </select>
                  </div>
                </li>
              </ul>
              <div class="phantom-option option" data-bind="click: addOption, css: input_type">
                <div class="li">
                  <div class="dummy-input"><%= t(".add_new_option") %></div> 
                </div>
              </div>
            </div>     
          </div>

          <div class="example" data-bind="visible: input_type() != 'select' && input_type() != 'select1' && input_type() != 'note'">
            <div class="col-md-3 label-text">
              <%= t(".example") %>
            </div>
            <div class="col-md-9 example-type">
              <p data-bind="visible: input_type() == 'date'"><%= t(".preview.date") %></p>
              <p data-bind="visible: input_type() == 'text'">Abc</p>
              <p data-bind="visible: input_type() == 'number'">123</p>
              <p data-bind="visible: input_type() == 'location'">Lat: 42.3609509, Lon: -71.0870836</p>
              <p data-bind="visible: input_type() == 'image'">
                <span class="glyphicon glyphicon-picture"></span>
              </p>
            </div>
          </div>
        </div>

        <div class="row required" data-bind="visible: input_type() != 'note'">
          <div class="col-md-3"></div>
          <div class="col-md-9">
            <input type="checkbox" data-bind="checked: required"> <label><%= t(".required") %></label>
          </div>
        </div>

        <div class="save right">
          <div class="btn btn-info" data-bind="click: save">
            <%= t("defaults.save")%>
          </div>
        </div>
        <!-- /ko -->

        <!-- ko ifnot: inEdit -->
        <div class="modify">
          <a href="#" class="btn" data-bind="click: edit"><%= t("defaults.edit") %></a>
          <a href="#" class="btn" title="<%= t("defaults.copy") %>" data-bind="click: copy"><i class="fa fa-copy"></i></a>
          <a href="#" class="btn" title="<%= t("defaults.delete") %>" data-bind="click: $parent.removeInput"><i class="glyphicon glyphicon-trash"></i></a>
        </div>
        <div class="reorder">
          <span class="jump-to glyphicon glyphicon-random active" data-bind="visible: options()[0] && options()[0].jump_to"></span>
        </div>

        <p data-bind="text: $data.label" class="label-text"></p>
        <div class="example" data-bind="css: input_type">
          <div class="options" data-bind="visible: input_type() === 'select' || input_type() === 'select1'">
            <p data-bind="visible: input_type() === 'select'"><%= t(".select_many") %>:</p>
            <p data-bind="visible: input_type() === 'select1'"><%= t(".select_one") %>:</p>
            <ul class="answer" data-bind="foreach: options, valueUpdate:'input', css: input_type">
              <li class="option">
                <p class="inline" data-bind="text: label, valueUpdate:'input'"></p><br>
                <p class="inline jump-to" data-bind="visible: jump_to"><%= t(".jump-to") %>: <span data-bind="text: jump_to ? PT.survey.getLabelById(jump_to) : false, valueUpdate:'input'"></span></p>
              </li>
            </ul>
          </div>
          <p data-bind="visible: input_type() == 'date'"><%= t(".preview.date") %></p>
          <p data-bind="visible: input_type() == 'text'">Abc</p>
          <p data-bind="visible: input_type() == 'number'">123</p>
          <p data-bind="visible: input_type() == 'location'">Lat: 42.3609509, Lon: -71.0870836</p>
          <p data-bind="visible: input_type() == 'image'">
            <span class="glyphicon glyphicon-picture"></span>
          </p>
        </div>
        <p class="subtle required-input" data-bind="visible: required()">
          * <%= t(".required") %>
        </p>
        <!-- /ko -->
        <div class="error messages"></div>
      </li>
    </ol>
    <div id="on-canvas-controls">
      <div class="tool-button btn btn-default">
        <span class="glyphicon glyphicon-plus"></span><br>
      </div>
    </div>
  </div>
</div>

<% if @survey && @survey.id %>
  <script type="text/javascript">
    PT.input_types = <%= raw @input_types %>;
    PT.getSurvey("<%= @survey.id %>");
    // $(document).on("click", ".jump-to-expand", function(event){
    //   $(this).parent().find(".jump-to-content").toggle(300);
    //   return false;
    // });
  </script>
<% end %>

app/views/surveys/_survey_builder.html.erb
<div id="workspace">
  <div class="campaign-title inline"><%= @survey.title %></div>

  <!-- Survey body -->
  <%= render partial: 'survey_body' %>
 
  <!-- Done button -->
  <div class="controls">
    <% if current_user %>
    <button class="btn btn-info" data-bind="click: saveOrder"><%= t('.finalize_survey') %></button>
    <% end %>
  </div>

  <!-- Sidebar -->
  <div id="sidebar">
    <div id="sidebar-header">
      <h3 class="title" ><%= t(".preview_title") %></h3>
    </div>
    <div id="preview" style="display: none;" data-bind="visible: true">
      <%= render 'android_preview' %>
    <div>
  </div>
</div>

<script type="text/javascript">  

  $("#input-list").sortable({
    handle: ".reorder",
    stop: function(event, ui){
      ui.item.addClass("drag-insert");
      ui.item.trigger("click");
    }
  });

  // Add new answer option on enter key
  $(document).on("keyup", ".options", function(){
    if(event.keyCode == 13){
      $(event.currentTarget).find(".phantom-option").click()
    }
  });
</script>

app/views/surveys/edit.html.erb
<%= render 'survey_builder' %>

app/views/surveys/fill_out.html.erb
<div class="container">
  Fill out Survey page
</div>

<script type="text/javascript">
  PT.retrieveSurveyDefinition(<%= @code %>, function(){

  });
</script>

app/views/surveys/launch.html.erb
<div class="page-container">
  <h1><%= link_to @survey.title, survey_path(@survey) %></h1>

  <% if @survey.status == "draft" %>
    <h2><%= t(".launch_title") %></h2>
    <%= t(".launch_info") %>
    <br><br>
    <%= link_to t(".return_to_edit"), survey_path(@survey), class: "btn btn-default" %>
    <%= link_to preview_survey_path(@survey), class: "btn btn-info open-preview", target: "_blank" do %>
      <i class="icon-mobile-phone"></i> <%= t(".preview") %>
    <% end %>
    <%= link_to t(".launch_survey"), activate_survey_path(@survey), class: "btn btn-warning", data: { confirm: t(".launch_confirmation") } %>

  <% elsif @survey.status == "active"  %>
    <%= t(".active") %><br>
    Overview:<br><br>
    <%= link_to t(".close"), close_survey_path(@survey), class: "btn btn-warning", confirm: t(".close_confirmation") %>

  <% else %>
    <%= t(".closed") %>
  <% end %>
</div>

app/views/surveys/new.html.erb
<%= render 'survey_builder' %>

<script type="text/javascript">

  $('#new-survey-modal').on('modal', function(e){
      debugger
      e.preventDefault();
  });
  PT.survey = new PT.SurveyModel();
  PT.survey.campaign_id = <%= raw @campaign.id %>;
  PT.selectedInput = ko.observable();
  ko.applyBindings(PT.survey);
  $(document).on("click", ".tool-button", PT.survey.addInput);
  $("#launch-survey").on("click", PT.launchSurvey);
</script>

app/views/surveys/show.html.erb
<%= render 'survey_builder' %>

app/views/surveys/show.xml.erb
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa">
  <h:head>
    <h:title><%= @survey.title %></h:title>
    <model>
      <instance>
        <data id="<%= @survey.guid %>">
          <meta>
            <instanceID/>
          </meta>
          <% @survey.inputs.each do |input| %>
          <<%= input.guid %>/>
          <% end %>
        </data>
      </instance>
      <itext>
        <translation lang="eng">
          <% @survey.inputs.each do |input| %>
          <text id="/data/<%= input.guid %>:label">
            <value><%= input.label %></value>
          </text>  
          <% if input.options %>
          <% input.options.values.each_with_index do |label, index| %>
          <text id="/data/<%= input.guid %>:option<%= index %>">
            <value><%= label %></value>
          </text>
          <% end %> 
          <% end %>  
          <% end %>
        </translation>
      </itext>
      <bind nodeset="/data/meta/instanceID" type="string" readonly="true()" calculate="concat('uuid:', uuid())"/>
      <% @survey.inputs.each do |input| %>
      <bind nodeset="/data/<%= input.guid %>" type="<%= input.input_type %>"/>
      <% end %>
    </model>
  </h:head>
  <h:body>
    <% @survey.inputs.each do |input| %>
    <%= render_xml(input) %>
    <% end %> 
  </h:body>
</h:html>

app/views/surveys/test_builder.html.erb
<%= render 'survey_builder' %>

<script type="text/javascript">
  PT.survey = new PT.SurveyModel();
  PT.selectedInput = ko.observable();
  ko.applyBindings(PT.survey);
  $(document).on("click", ".tool-button", PT.survey.addInput);
  $("#launch-survey").on("click", PT.launchSurvey);
</script>