config/routes.rb
PromiseTracker::Application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }
  root to: 'home#index'
  match ':status', via: [:get, :post], to: 'errors#show', constraints: {status: /\d{3}/ }

  scope "(:locale)", locale: /en|pt-BR|es|de/ do
    resources :users
    resources :campaigns
    resources :surveys, except: [:index] do
      resources :inputs
    end

    get '/surveys/:id/preview', to: 'surveys#preview', as: 'preview_survey'
    get '/surveys/test', to: 'surveys#test_builder', as: 'test_builder'
    put '/surveys/:id/save-order', to: 'surveys#save_order', as: 'save_order'
    get '/campaigns/:id/setup', to: 'campaigns#setup', as: 'setup_campaign'
    get '/campaigns/:id/goals-wizard', to: 'campaigns#goals_wizard', as: 'campaign_goals_wizard'
    get '/campaigns/:id/goals', to: 'campaigns#goals', as: 'campaign_goals'
    get '/campaigns/:id/launch', to: 'campaigns#launch', as: 'launch_campaign'
    get '/campaigns/:id/survey', to: 'campaigns#survey', as: 'campaign_survey'
    get '/campaigns/:id/profile', to: 'campaigns#profile', as: 'campaign_profile'
    get '/campaigns/:id/edit-profile', to: 'campaigns#edit_profile', as: 'edit_campaign_profile'
    get '/campaigns/:id/public', to: 'campaigns#public_profile', as: 'campaign_public_profile'
    get '/campaigns/:id/test', to: 'campaigns#test', as: 'test_campaign'
    get '/campaigns/:id/collect', to: 'campaigns#collect', as: 'campaign_collect'
    get '/campaigns/:id/share', to: 'campaigns#share', as: 'share_campaign'
    get '/campaigns/:id/close', to: 'campaigns#close', as: 'close_campaign'
    get '/campaigns/:id/next', to: 'campaigns#next', as: 'campaign_next'
    post '/campaigns/:id/activate', to: 'campaigns#activate', as: 'activate_campaign'
    post '/campaigns/:id/clone', to: 'campaigns#clone', as: 'clone_campaign'

    post '/inputs/:id/clone', to: 'inputs#clone', as: 'clone_input'

    get '/download', to: 'home#download', as: 'download'
    get '/stats', to: 'campaigns#get_stats', as: 'stats'
    get '/guides', to: 'home#guides', as: 'guides'
    get '/data/:code', to: 'campaigns#share', as: 'share_campaign_code'
    get '/codigo/:code', to: 'surveys#fill_out', as: 'fill_out_survey'
    get '/help', to: "home#help", as: 'help'
  end

  namespace :api do
    namespace :v1 do
      resources :campaigns, only: [:index, :show, :create]
      get '/users/sign_in', to: 'users#create_new_session', as: 'api_sign_in'
    end
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user
  has_one :survey
  has_and_belongs_to_many :tags
  has_attached_file :image, default_url: '/assets/placeholder.jpg'

  validates :title, length: { minimum: 5 }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/ 

  STATUS =  ['draft', 'test', 'active', 'closed']

  def translated_themes
    I18n.t(:themes, :scope => 'campaigns.edit')
  end

  def clone
    clone = self.dup
    clone.tags = self.tags
    clone.update_attributes(
      status: 'draft',
      organizers: nil,
      anonymous: nil,
      start_date: nil,
      end_date: nil,
      image: nil,
      campaign_page_valid: false
    )
    clone.save
    clone
  end

  def validate_goals
    self.title.present?
    self.description.present? && 
    self.organizers.present? && 
    self.audience.present? &&  
    self.submissions_target.present?
  end

  def draft?
    self.status == 'draft' || self.status == 'test'
  end

  def get_latest_state
    if self.status == 'closed'
      'share'
    elsif self.status == 'active'
      'collect'
    elsif self.status == 'test'
      'test'
    elsif self.campaign_page_valid
      'edit_profile'
    elsif self.survey || self.validate_goals
      'survey'
    else
      'edit'
    end
  end

end

app/controllers/api/v1/campaigns_controller.rb
include ActionController::HttpAuthentication::Token

module Api
  module V1
    class CampaignsController < ApplicationController
      before_filter :restrict_access
      protect_from_forgery with: :null_session, except: [:create]

      def index
        if params[:tags]
          @campaigns = params[:tags].map do |tag|
            tag = Tag.find_by(label: tag)
            tag.campaigns if tag
          end.reduce do |a, b|
            a || b
          end.select { |c| !c.draft? }
          render 'index', formats: [:json]
        elsif params[:user_id]
          api_key = ApiKey.find_by(access_token: token_and_options(request)[0])
          user = User.where(
            api_client_name: api_key.client_name,
            api_client_user_id: params[:user_id]).first

          if user
            @campaigns = user.campaigns
            render 'index', formats: [:json]
          else
            @error_code = 23
            @error_message = 'User not found'
            render 'api/v1/error', formats: [:json], status: 404
          end
        else
          @campaigns = Campaign.includes(:tags).where.not(status: 'draft')
          render 'index', formats: [:json]
        end
      end

      def show
        @campaign = Campaign.includes(:tags, survey: :inputs).find_by_id(params[:id])
        @user = User.where(api_client_user_id: params[:user_id].to_i).first
        user_id = @user ? @user.id : nil

        if @campaign
          if @campaign.status == 'draft' && @campaign.user_id != user_id
            @error_code = 21
            @error_message = 'Campaign has not been published'
            render 'api/v1/error', format: :json, status: 401
          else
            render 'show', formats: [:json]
          end
        else
          @error_code = 18
          @error_message = 'Campaign not found'
          render 'api/v1/error', formats: [:json], status: 404
        end
      end

      def create
        api_key = token_and_options(request)[0]

        if params[:user_id] && params[:username]
          user = User.find_or_create_api_user(
            params[:user_id],
            params[:username],
            api_key)

          if params[:campaign_id]
            existing_campaign = Campaign.find_by(id: params[:campaign_id])

            if existing_campaign
              campaign = existing_campaign.clone
            else
              @error_code = 18
              @error_message = 'Campaign not found'
              render 'api/v1/error', formats: [:json], status: 404 and return
            end
          else
            campaign = Campaign.create
            campaign.tags = params[:tags] if params[:tags]
          end

          campaign.user_id = user.id
          campaign.save(validate: false)
          render json: {
            status: "success",
            payload: {
              redirect_link: "#{request.url.split("api").first}api/v1/users/sign_in?user_id=#{user.api_client_user_id}&username=#{params[:username]}&campaign_id=#{campaign.id}&token=#{api_key}&locale=pt-BR"
            }
          }.to_json
        else
          @error_code = 22
          @error_message = 'User id and username required'
          render 'api/v1/error', formats: [:json], status: 401
        end
      end
    end
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  layout 'campaign', except: [:index, :public_profile, :setup, :get_stats]
  before_filter :authenticate_user!, except: [:public_profile, :share]
  before_filter :restrict_user_access, except: [:create, :index, :public_profile, :share, :clone, :get_stats]
  before_filter :assign_campaign_variables, except: [:index, :create, :destroy, :share, :get_stats]

  def index
    @campaign = Campaign.new
    @campaigns = current_user.campaigns.select{ |c| c.title.present? }.sort_by(&:status)
  end

  def new
    @campaign = Campaign.find(params[:id])
  end

  def create
    @campaign = current_user.campaigns.find_or_create_by(id: params[:campaign][:id])
    @campaign.update_attributes(campaign_params)
    if campaign_params[:city]
      tag = Tag.find_or_create_by(label: campaign_params[:city])
      @campaign.tags.push(tag)
    end
    redirect_to edit_campaign_path(@campaign)
  end

  def show
    redirect_to action: @campaign.get_latest_state, id: @campaign.id
  end

  def goals
  end

  def next
    permission = campaign_can_advance?(params[:refer_action])

    if permission == true
      redirect_to action: get_next_state(params[:refer_action]), id: @campaign.id
    else
      redirect_to :back, flash: { error: permission }
    end
  end

  def goals_wizard
  end

  def edit
  end

  def update
    @campaign = Campaign.find(params[:id])
    @campaign.update_attributes(campaign_params)
    
    if @campaign.survey
      @campaign.survey.update_attribute(:title, @campaign.title)
    end

    if params[:campaign][:redirect_action] && @campaign.campaign_page_valid
      redirect_to action: params[:campaign][:redirect_action]
    else
      redirect_to action: @campaign.get_latest_state, id: @campaign.id
    end
  end

  def survey
    @input_types = input_types.to_json
  end

  def profile
    @input_types = input_types.to_json
    if !current_user
      render layout: 'application'
    end
  end

  def edit_profile
    @input_types = input_types.to_json
  end

  def public_profile
    @input_types = input_types.to_json
  end

  def setup
  end

  def test
    @input_types = input_types.to_json
    if @campaign.status == 'draft'
      @survey.activate('test')
    end
  end

  def activate
    if @survey.activate(params[:status])['status'] == 'success'
      if params[:status] == 'test'
        redirect_to test_campaign_path(@campaign)
      elsif params[:status] == 'active'
        redirect_to campaign_collect_path(@campaign)
      end
    else
      redirect_to request.referer, flash: {error: t('.upload_error')}
    end
  end

  def collect
  end

  def share
    assign_campaign_variables
    @input_types = input_types.to_json
  end

  def close
    if @survey.close['status'] == 'success'
      @campaign.update_attribute(:status, 'closed')
      redirect_to share_campaign_path(@campaign)
    else
      render 'collect'
    end
  end

  def clone
    campaign_clone = @campaign.clone
    title = @campaign.title + " #{t('campaigns.status.copy')}"
    campaign_clone.update_attributes(
      title: title + " #{Campaign.where(title: title).count if Campaign.where(title: title).count > 0}",
      organizers: nil,
      status: 'draft'
    )

    if @campaign.survey
      campaign_clone.survey = @campaign.survey.clone
      campaign_clone.survey.update_attribute(:title, campaign_clone.title)
    end

    current_user.campaigns << campaign_clone
    redirect_to edit_campaign_path(campaign_clone)
  end

  def destroy
    Campaign.delete(params[:id])
    redirect_to campaigns_path
  end

  def get_stats
    @users = User.all
    @campaigns = Campaign.all
  end


  private

  def restrict_user_access
    @campaign = Campaign.find(params[:id])
    raise Exceptions::Forbidden unless current_user.owns?(@campaign)
  end

  def get_next_state(current_action)
    case current_action
    when 'edit', 'goals_wizard', 'goals'
      'survey'
    when 'survey'
      'edit_profile'
    when 'edit_profile', 'profile'
      'test'
    when 'test'
      'collect'
    end
  end

  def campaign_can_advance?(current_action)
    case current_action
    when 'edit', 'goals_wizard'
      t('defaults.validations.please_define_goals')
    when 'goals'
      true
    when 'survey'
      if @survey && @survey.inputs.length > 0
        true
      else
        t('defaults.validations.please_create_survey')
      end
    when 'edit_profile', 'profile'
      if @campaign.campaign_page_valid
        true
      else
        t('defaults.validations.please_complete_campaign_page')
      end
    when 'test'
      if @campaign.status == 'active'
        true
      else
        t('defaults.validations.launch_campaign')
      end
    end
  end

  def assign_campaign_variables
    find_campaign_by_id_or_code
    @can_advance = campaign_can_advance?(params[:action])
  end

  def find_campaign_by_id_or_code
    if params[:id]
      @campaign = Campaign.includes(survey: :inputs).find(params[:id])
      @survey = @campaign.survey
    elsif params[:code]
      @survey = Survey.includes(:inputs, :campaign).find_by(code: params[:code].split("-").join)
      @campaign = @survey.campaign
    end
  end

  def campaign_params
    params.require(:campaign).permit(
      :title, :description, :goal, :theme, :data_collectors,
      :submissions_target, :audience, :organizers, :anonymous, :image, :campaign_page_valid, :country, :city)
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def campaign_themes
    I18n.t("activerecord.options.themes").map { |key, value| [ value, key ] }
  end

  def campaign_countries
    I18n.t("activerecord.options.countries").map { |key, value| [ value, key ] }
  end
  
end

app/views/campaigns/_campaign_header.html.erb
<% if current_user && current_user.owns?(@campaign) %>
  <%= render partial: 'campaigns/progress_bar' %>

  <% if !@campaign.draft? %>
    <%= render partial: 'tabs' %>
  <% end %>
<% end %>

<% if action_name != 'edit' && action_name != 'goals_wizard' %>
  <div class="campaign-title section-container">
    <%= link_to @campaign.title, campaign_path(@campaign) %>
    <% if @campaign.status != "draft" %>
      <% if action_name != 'share'%>
        <span class="subtle small"> (<%= format_survey_code(@survey.code) %>)</span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/campaigns/_data.html.erb
<div class="campaign-data">
  <div id="map-viz">
    <div id="report-map-container"></div>
  </div>
  
  <div id="graph-viz">
    <div id="report-graph-container">

      <!-- Slides container -->
      <div id="graph-carousel" class="carousel slide" data-ride="carousel" data-wrap="false">
        <div id="slides-container"></div>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/_list_item.html.erb
<li class="row">
  <div class="col-sm-8 campaign-name">
    <%= link_to campaign_path(campaign) do %>
      <div class="status-icon <%= campaign.status %> inline"></div>
      <div class="campaign-link"><%= campaign.title %></div>
    <% end %>
  </div>

  <div class="col-sm-4 modify">
    <%= link_to campaign_path(campaign) do %>
      <span class="glyphicon glyphicon-flag <%= campaign.status %>"></span>
      <%= t("campaigns.status.#{campaign.status}") %>
    <% end %>
    <%= link_to clone_campaign_path(campaign), class: "pad-side", title: t("defaults.copy"), method: :post do %>
      <i class="fa fa-files-o"></i>
    <% end %>
    <%= link_to campaign_path(campaign), class: "pad-side", title: t("defaults.delete"), method: :delete, data: { confirm: t(".confirm_delete") } do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </div>
</li>

app/views/campaigns/_new.html.erb
<div class="modal fade" id="new-campaign-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= t(".modal_title") %></h4>
      </div>

      <%= form_for @campaign do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :theme, t(".campaign_theme") %>
            <%= f.select :theme, campaign_themes, {}, { class: "form-control auto-width" } %>
          </div>
          <br>
          <div class="form-group">
            <%= f.label :title, t(".campaign_title") %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div id="errors">
            <ul></ul>
          </div> 
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-info"><%= t(".create_campaign") %></button>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/campaigns/_viz_panel.html.erb
<!--     Filter panel -->
<div class="filters collapse-group">
  <div class="header">
    <div><%= t("campaigns.share.filters")%> <span class="control glyphicon glyphicon-chevron-down"></span></div>
  </div>
  <div class="content collapse col-md-10">
    <div class="date-range-container filter filter-field">
      <div class="name col-md-1"><%= t("campaigns.share.date")%></div>
      <div class="col-md-11 control">
        <div id="date-range"></div>
      </div>
      <div class="read-out col-md-12"></div>
    </div>
    <div class="field-container filter">
      <div class="name col-md-1"><%= t("campaigns.share.question")%></div>
      <div class="col-md-11 control">
        <select id="select-field"></select>
        <select id="select-value" class="filter-field"></select>
      </div>
    </div>
  </div>
</div>

<div class="viz-panel">
  <div class="featured-viz tab-content">

    <div class="tab-pane fade in active" id="graph-viz">
      <div id="graph-container" class="row"></div>
      <div class="ajax-loading">
        <%= image_tag("ajax-loader.gif") %>
        <h4><%= t("defaults.loading") %></h4>
      </div>
      <div id="graph-placeholder">
        <h3><%= t(".graph_placeholder") %></h3>
        <div id="graph-images">
          <%= image_tag("graphs-pie.png") %>
          <%= image_tag("graphs-column.png") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/edit.html.erb
<div class="section-container">
  <%= form_for @campaign do |f| %>
    <div class="section-header">
      <%= f.text_field :title, class: "campaign-title" %>
      <div class="right">
        <%= f.submit t("defaults.save"), class: "btn btn-info" %>
      </div>
      <h2 class="title sub-title"><%= t("campaigns.progress_bar.define_goals") %></h2>
    </div>

    <div id="campaign-goals-form" class="single-page">
      <div class="row">
        <div class="col-sm-3 block">
          <div class="form-group">
            <%= f.label :theme, class: "block" %>
            <%= f.select :theme, campaign_themes, {}, { class: "form-control" } %> 
          </div>
        </div>
        <div class="col-md-5 form-group">
          <%= f.label :city, Campaign.human_attribute_name(:city) %>
          <%= f.text_field :city, class: "form-control" %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-8">
          <div class="form-group"> 
            <%= f.label :description %>
            <p class="explain"><%= t("campaigns.edit.explanations.description") %></p>
            <%= f.text_area :description, rows: 5, class: "form-control", autofocus: true %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-8">
          <div class="form-group"> 
            <%= f.label :organizers %>
            <p class="explain"><%= t("campaigns.edit.explanations.organizers") %></p>
            <%= f.text_area :organizers, rows: 2, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-8">
          <div class="form-group"> 
            <%= f.label :submissions_target %>
            <p class="explain"><%= t(".explanations.submissions_target") %></p>
            <%= f.number_field :submissions_target, min: 0, class: "block" %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="tip-box">
            <div class="header">
              <span class="icon-question-sign"></span> <%= t(".tooltip") %>
            </div>
            <div class="body">
              <p><%= t(".tips.submissions_target") %></p>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-8">
          <div class="form-group"> 
            <%= f.label :audience %>
            <p class="explain"><%= t(".explanations.audience") %></p>
            <%= f.text_area :audience, rows: 5, class: "form-control" %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="tip-box">
            <div class="header">
              <span class="icon-question-sign"></span> <%= t(".tooltip") %>
            </div>
            <div class="body">
              <p><%= t(".tips.audience") %></p>
            </div>
          </div>  
        </div>

        <div class="button-group center clear">
          <hr>
          <%= f.hidden_field :redirect_action, value: "goals" %>
          <%= f.submit t("defaults.save"), class: "btn btn-info" %>
        </div>
      </div>
    </div> 
  <% end %>
</div>

<script type="text/javascript">
  $(document).on("click", ".tip-box", PT.toggleTip);
  $(".right-arrow").on("click", PT.nextFormPage);
  $(".left-arrow").on("click", PT.previousFormPage);
  $()

  $("#update-title-button").on("click", function(){
    PT.updateDisplay($("#campaign-title-input"), $(".campaign-title"));
  });

  $("textarea, input").on("click", function(){
    var $currentTip = $(this).parents(".row").find(".tip-box .body");
    $(".tip-box .body").not($currentTip).slideUp();
    $currentTip.slideDown();
  });

  $(".edit_campaign").on("submit", function(){
    if(!PT.validateOverview(this)){
      PT.scrollToError();
      return false;
    }
  });
</script>

app/views/campaigns/profile.html.erb
<div class="section-container">
  <% if current_user && current_user.owns?(@campaign) %>
    <div class="section-header">
      <h2 class="title sub-title inline"><%= t("campaigns.campaign_page.title") %></h2>
      <div class="right">
        <%= link_to t("campaigns.campaign_page.view_as_public"), campaign_public_profile_path(@campaign), target: "blank", class: "pad-side subtle small" %>
        <%= link_to t("defaults.edit"), edit_campaign_profile_path(@campaign), class: "btn btn-info" %>
      </div>
    </div>
  <% end %>

  <div class="preview">
    <div class="section grey">
      <div class="section-container grey pad-top">
        <%= render partial: 'profile' %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  // Facebook SDK
    window.fbAsyncInit = function() {
    FB.init({
      appId            : '337756186420908',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : 'v2.10'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

  // Facebook share handler
  $(document).on("click", ".fb-share-button", function(){
    FB.ui({
      method: 'share',
      href: '<%= "#{request.original_url.split('campaigns/').first}campaigns/#{@campaign.id}/public" %>',
    }, function(response){
    });
  });

  // Fetch responses from aggregator
  <% if @campaign.status == "closed" %>
    PT.retrieveResponses(<%= @campaign.survey.code %>, function(data){
      PT.renderGoogleMap(data, "report-map-container");
      PT.populateImages(data.responses, "#report-image-container");
      PT.renderReportGraphs(data.responses, "#slides-container");
    });
  <% end %>
</script>

app/views/campaigns/survey.html.erb
<div class="section-container">
  <div id="campaign-survey">
    <div class="section-header">
      <h2 class="title sub-title inline"><%= Survey.model_name.human %></h2>
      <% if @survey && @campaign.draft? %>
        <div class="right">
          <%= link_to t(".edit_survey"), edit_survey_path(@survey), class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
    <div class="section-body center">
      <% if @survey %>
        <%= render partial: 'surveys/survey_body' %>
      <% else %>
        <%= link_to new_survey_path(campaign_id: @campaign.id), class: "btn btn-info new-survey-button" do %>
          <span class="glyphicon glyphicon-plus-sign"></span>
          <%= t("campaigns.progress_bar.create_survey") %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<br>

<script type="text/javascript">
  $("#input-list").sortable({ disabled: true });
</script>

app/views/campaigns/test.html.erb
<div id="test-campaign" class="section-container participate">
  <% if @campaign.draft? %>
    <div class="section-header">
      <h2 class="title sub-title inline"><%= t(".test_title") %></h2>
      <div class="right padded text-right">
        <%= link_to t(".edit_survey"), edit_survey_path(@survey), class: "btn btn-info margin-bottom" %>
        <%= link_to t(".go_live"), activate_campaign_path(id: @campaign.id, status: "active"), method: :post, class: "btn btn-warning", data: { confirm: t(".confirm_launch") } %>
      </div>
    </div>
    <p class="partial upsize">
      <%= t(".test_explanation") %> 
      <%= t(".catch_errors") %> 
      <strong><%= t(".warning") %></strong>
    </p>
    <br>

    <ul id="test-tabs" class="nav nav-tabs" role="tablist">
      <li>
        <a href="#how-to-test" role="tab" data-toggle="tab" class="active" id="instructions-tab">
          <h3 class="title">
            <%= t(".how_to_test") %>
          </h3>
        </a>
      </li>
      <li>
        <a href="#view-data" role="tab" data-toggle="tab" id="view-data-tab">
          <h3 class="title">
            <%= t(".view_test_data") %>
          </h3>
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="how-to-test" class="tab-pane fade in active">
        <div class="row">
          <div id="how-to-participate" class="participate">
            <div class="row how-to-steps">
              <div class="col-sm-4">
                <div class="step">
                  <h5><%= t("campaigns.how_to_participate.step") %> 1:</h5><%= image_tag("pt-qr-code.png", class: "qr-code") %>
                  <h4><%= t("campaigns.how_to_participate.step_1_text") %></h4>
                  <%= link_to t("campaigns.how_to_participate.download_link"), download_path, target: "blank" %>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="step">
                  <h5><%= t("campaigns.how_to_participate.step") %> 2:</h5>
                  <i class="fa fa-download"></i>
                  <h4><%= t("campaigns.how_to_participate.step_2_text") %></h4>
                  <p class="small"><%= t("campaigns.how_to_participate.step_2_subtext") %>:</p>
                  <h3 class="code subtle"><%= format_survey_code(@survey.code) %></h3>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="step">
                  <h5><%= t("campaigns.how_to_participate.step") %> 3:</h5>
                  <i class="fa fa-check"></i>
                  <h4><%= t("campaigns.how_to_participate.step_3_text") %></h4>
                  <p class="small"><%= t("campaigns.how_to_participate.step_3_subtext") %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div id="view-data" class="tab-pane">
        <%= render partial: 'viz_panel' %>
      </div>
    </div>
  <% else %>
    <h3 class="title center test-complete">
      <i class="fa fa-check-circle turquoise"></i> <%= t(".test_complete") %>!<br>
      <%= t(".this_campaign_is") %> <%= link_to t("campaigns.status.#{@campaign.status}").downcase, campaign_path(@campaign) %>.
    </h3>
  <% end %>
</div>

<script type="text/javascript">
  $("#test-tabs a").click(function(e) {
    e.preventDefault();
    $(this).tab("show");
    $("#test-tabs a").removeClass("active");
    $(this).addClass("active");
  });

  // Fetch responses from aggregator
  PT.retrieveResponses(<%= @campaign.survey.code %>, function(data){

    // Populate panel
    PT.renderInputSummaries(PT.responses, "#graph-container", "col-md-5");
    PT.renderGallery(PT.responses, "#image-viz", "main-gallery");
    PT.renderGoogleMap(data, "map-viz");

    // Add map popup window
    var $popup = $(HandlebarsTemplates["response_view"](PT.surveyDefinition));
    $popup.addClass("popup");
    $popup.hide();
    $(document.body).append($popup);

    $(document).on("click", function(){
      $popup.hide();
    });

    // Switch to data tab if responses available
    var responseCount = PT.responses.length;
    if(responseCount > 0){
      $("#view-data-tab").trigger("click")
    }
  });
  
  $("#viz-tabs a").click(function(e) {
    e.preventDefault();
    $(this).tab("show");
    $("#viz-tabs a").removeClass("active");
    $(this).addClass("active");
  });

  // Re render graphs when graph tab clicked
  $("#graph-tab").on("shown.bs.tab", function(e){
    PT.renderInputSummaries(PT.aggregate, "#graph-container", "col-md-5");
  });
</script>