config/routes.rb
PromiseTracker::Application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }
  root to: 'home#index'
  match ':status', via: [:get, :post], to: 'errors#show', constraints: {status: /\d{3}/ }

  scope "(:locale)", locale: /en|pt-BR|es|de/ do
    resources :users
    resources :campaigns
    resources :surveys, except: [:index] do
      resources :inputs
    end

    get '/surveys/:id/preview', to: 'surveys#preview', as: 'preview_survey'
    get '/surveys/test', to: 'surveys#test_builder', as: 'test_builder'
    put '/surveys/:id/save-order', to: 'surveys#save_order', as: 'save_order'
    get '/campaigns/:id/setup', to: 'campaigns#setup', as: 'setup_campaign'
    get '/campaigns/:id/goals-wizard', to: 'campaigns#goals_wizard', as: 'campaign_goals_wizard'
    get '/campaigns/:id/goals', to: 'campaigns#goals', as: 'campaign_goals'
    get '/campaigns/:id/launch', to: 'campaigns#launch', as: 'launch_campaign'
    get '/campaigns/:id/survey', to: 'campaigns#survey', as: 'campaign_survey'
    get '/campaigns/:id/profile', to: 'campaigns#profile', as: 'campaign_profile'
    get '/campaigns/:id/edit-profile', to: 'campaigns#edit_profile', as: 'edit_campaign_profile'
    get '/campaigns/:id/public', to: 'campaigns#public_profile', as: 'campaign_public_profile'
    get '/campaigns/:id/test', to: 'campaigns#test', as: 'test_campaign'
    get '/campaigns/:id/collect', to: 'campaigns#collect', as: 'campaign_collect'
    get '/campaigns/:id/share', to: 'campaigns#share', as: 'share_campaign'
    get '/campaigns/:id/close', to: 'campaigns#close', as: 'close_campaign'
    get '/campaigns/:id/next', to: 'campaigns#next', as: 'campaign_next'
    post '/campaigns/:id/activate', to: 'campaigns#activate', as: 'activate_campaign'
    post '/campaigns/:id/clone', to: 'campaigns#clone', as: 'clone_campaign'

    post '/inputs/:id/clone', to: 'inputs#clone', as: 'clone_input'

    get '/download', to: 'home#download', as: 'download'
    get '/stats', to: 'campaigns#get_stats', as: 'stats'
    get '/guides', to: 'home#guides', as: 'guides'
    get '/data/:code', to: 'campaigns#share', as: 'share_campaign_code'
    get '/codigo/:code', to: 'surveys#fill_out', as: 'fill_out_survey'
    get '/help', to: "home#help", as: 'help'
  end

  namespace :api do
    namespace :v1 do
      resources :campaigns, only: [:index, :show, :create]
      get '/users/sign_in', to: 'users#create_new_session', as: 'api_sign_in'
    end
  end
end

app/views/layouts/_flash_messages.html.erb
<div class="flash-messages">
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <%- end -%>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <div class="navbar-header header-container">
    <div id="branding">
      <% if current_user %>
        <%= link_to campaigns_path, class: "home-button" do %>
          <%= image_tag("PT-logo.png") %>
        <% end %>
      <% else %>
        <%= link_to root_path, class: "home-button" do %>
          <%= image_tag("PT-logo.png") %>
        <% end %>
      <% end %>
      <h2 class="light inline site-title"><%= t("app_name")%></h2>
    </div>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-links" id="nav-button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>  
  </div>
  <div class="collapse navbar-collapse header-container" id="nav-links">
    <nav>
      <ul class="nav navbar-nav user-links">
        <% if current_user %>
          <li>
            <%= link_to campaigns_path do %>
              <%= image_tag("user-icon.png", class: "user-icon") %> <%= current_user.username %>
             <% end %> 
          </li>
          <li>
            <%= link_to t("devise.sign_out"), destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li><%= link_to t("devise.sign_in"), new_user_session_path, class: "btn" %></li>
        <% end %>    
        <% if I18n.locale == :en %>
          <li><%= link_to "Português", :locale=>'pt-BR' %></li>
        <% else %>
          <li><%= link_to "English", :locale=>'en' %></li>
        <%end%>

      </ul>
    </nav>  
  </div>
</div>

app/views/layouts/_include_links.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="<%= t('app_name') %>" >
<meta property="og:image" content='<%= URI.join(root_url, "assets/campaign-share-image-#{I18n.locale}.png") %>'>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

<link rel="shortcut icon" type="image/png" href="<%= asset_path("favicon.png")%>">
<link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400,300,600,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>

<script type="text/javascript">
  I18n.defaultLocale = "<%= I18n.default_locale %>";
  I18n.locale = "<%= I18n.locale %>";

  // Google analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60744513-4', 'auto');
  ga('send', 'pageview');
  

  // Facebook SDK
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '337756186420908',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

  //Twitter share handler
  window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
</script>

<div id="fb-root"></div>

app/views/layouts/_site_header.html.erb
<div id="header">
  <div class="navbar-header header-container">
    <div id="branding">
      <% if current_user %>
        <%= link_to campaigns_path, class: "home-button" do %>
          <%= image_tag("PT-logo.png") %>
        <% end %>
      <% else %>
        <%= link_to root_path, class: "home-button" do %>
          <%= image_tag("PT-logo.png") %>
        <% end %>
      <% end %>
      <h2 class="light inline site-title"><%= t("app_name")%></h2>
    </div>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-links" id="nav-button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>  
  </div>
  <div class="collapse navbar-collapse header-container" id="nav-links">
    <nav>
      <ul class="nav navbar-nav user-links">
        <% if current_user %>
          <li id="user-menu" class="dropdown" >
            <%= link_to campaigns_path do %>
              <%= image_tag(current_user.avatar.url(:thumb), class: "user-icon") %> <%= current_user.username %>
            <% end %> 
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t(".campaigns"), campaigns_path %></li>
              <li><%= link_to t(".account"), user_path(current_user) %></li>
              <% if I18n.locale == :"pt-BR" %>
              <li><%= link_to t(".guides"), guides_path %></li>
              <% end %>
              <li>
                <%= link_to t("devise.sign_out"), destroy_user_session_path, class: "highlight", method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("devise.sign_in"), new_user_session_path, class: "btn btn-info" %></li>
        <% end %>
        <li class="text-link">
          <%= link_to t(".help"), help_path %>
        </li>
        <li id="language-menu" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= t("locale_name") %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "English", :locale=>'en' %></li>
            <li><%= link_to "Português", :locale=>'pt-BR' %></li>
            <li><%= link_to "Español", :locale=>'es' %></li>
            <li><%= link_to "Deutsche", :locale=>'de' %></li>
          </ul>
        </li>
      </ul>
    </nav>  
  </div>
</div>

<!-- Flash messages -->
<% flash.each do |key, value| %>
  <div class="well lead flash" id="flash-temporary"><%= value %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %></title>
    <%= render partial: 'layouts/include_links' %>
    <%= yield :head %>
  </head>
  
  <body data-no-turbolink="true">
    <%= render "layouts/site_header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/campaign.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %></title>
    <%= render partial: 'layouts/include_links' %>
  </head>
  
  <body>
    <%= render 'layouts/site_header' %>
    <%= render 'campaigns/campaign_header' %>
    <%= yield %>
  </body>


  <script>
  
    //Campaign progress bar

    $("li[data-path ~= <%= action_name %>]").addClass("active");
    $("li[data-complete = true]").addClass("complete");
    $("li[data-clickable = false]").css("pointer-events", "none");

    $("#errors .close").on("click", function(){
      $(this).parent().hide();
    });

    //Navigations tabs

    $(".tab[data-action~=<%= action_name %>]").addClass("active");
    $(".tab[data-visible='false']").hide();

  </script>
</html>

app/views/layouts/preview.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %></title>
    <%= render partial: 'layouts/include_links' %>
  </head>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/survey_builder.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %></title>
    <%= render partial: 'layouts/include_links' %>
  </head>
  
  <body>
    <div id="header">
      <div class="navbar-header header-container">
        <div id="branding">
          <% if current_user %>
            <%= link_to campaigns_path, class: "home-button" do %>
              <%= image_tag("PT-logo.png") %>
            <% end %>
          <% else %>
            <%= link_to root_path, class: "home-button" do %>
              <%= image_tag("PT-logo.png") %>
            <% end %>
          <% end %>
          <h2 class="light inline site-title"><%= t('app_name') %></h2>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>